#!/usr/bin/env python3
"""Load a temporary domain-scoped Chrome extension and sync cookies to MediaFetch."""

import argparse
import hmac
import json
import os
import secrets
import subprocess
import sys
import tempfile
import threading
from http.server import BaseHTTPRequestHandler, ThreadingHTTPServer
from pathlib import Path
from typing import Any

import httpx

PLATFORM_DOMAINS: dict[str, tuple[str, ...]] = {
    "douyin": ("douyin.com", "iesdouyin.com"),
    "instagram": ("instagram.com",),
    "youtube": ("youtube.com", "google.com"),
}
MAX_REQUEST_BYTES = 1024 * 1024
MAX_COOKIE_FILE_BYTES = 128 * 1024


def _matches_domain(hostname: str, domains: tuple[str, ...]) -> bool:
    host = hostname.lstrip(".").lower().rstrip(".")
    return any(host == domain or host.endswith(f".{domain}") for domain in domains)


def _cookie_bytes(cookies: list[dict[str, Any]], domains: tuple[str, ...]) -> bytes:
    lines = ["# Netscape HTTP Cookie File", "# Generated by MediaFetch temporary extension"]
    seen: set[tuple[str, str, str]] = set()
    for item in cookies:
        domain = str(item.get("domain") or "")
        path = str(item.get("path") or "/")
        name = str(item.get("name") or "")
        value = str(item.get("value") or "")
        if not name or not value or not _matches_domain(domain, domains):
            continue
        fields = (domain, path, name, value)
        if any("\t" in field or "\r" in field or "\n" in field for field in fields):
            continue
        identity = (domain, path, name)
        if identity in seen:
            continue
        seen.add(identity)
        output_domain = f"#HttpOnly_{domain}" if item.get("httpOnly") else domain
        expiration = item.get("expirationDate")
        try:
            expires = str(max(0, int(float(expiration)))) if expiration else "0"
        except (TypeError, ValueError):
            expires = "0"
        lines.append(
            "\t".join(
                (
                    output_domain,
                    "TRUE" if domain.startswith(".") else "FALSE",
                    path,
                    "TRUE" if item.get("secure") else "FALSE",
                    expires,
                    name,
                    value,
                )
            )
        )
    content = ("\n".join(lines) + "\n").encode()
    if len(content) > MAX_COOKIE_FILE_BYTES:
        raise RuntimeError("Target platform cookies exceed 128 KiB")
    return content


def _upload(base_url: str, token: str, platform: str, content: bytes) -> bool:
    with httpx.Client(timeout=30, follow_redirects=False) as client:
        response = client.put(
            f"{base_url.rstrip('/')}/api/v1/admin/platforms/{platform}/cookies",
            headers={"X-Admin-Token": token},
            files={"file": (f"{platform}-cookies.txt", content, "text/plain")},
        )
    if response.status_code != 200:
        raise RuntimeError(f"HTTP {response.status_code}")
    return bool(response.json().get("configured"))


class SyncState:
    def __init__(self, nonce: str, base_url: str, token: str):
        self.nonce = nonce
        self.base_url = base_url
        self.token = token
        self.finished = threading.Event()
        self.result: dict[str, tuple[int, bool]] = {}
        self.error: str | None = None
        self.lock = threading.Lock()

    def synchronize(self, payload: object) -> None:
        with self.lock:
            if self.finished.is_set():
                return
            try:
                if not isinstance(payload, dict):
                    raise RuntimeError("Invalid extension payload")
                for platform, domains in PLATFORM_DOMAINS.items():
                    raw_cookies = payload.get(platform)
                    if not isinstance(raw_cookies, list):
                        raw_cookies = []
                    cookies = [item for item in raw_cookies if isinstance(item, dict)]
                    content = _cookie_bytes(cookies, domains)
                    count = max(0, content.count(b"\n") - 2)
                    configured = bool(count) and _upload(
                        self.base_url,
                        self.token,
                        platform,
                        content,
                    )
                    self.result[platform] = (count, configured)
            except Exception as exc:
                self.error = f"{type(exc).__name__}: {exc}"
            finally:
                self.finished.set()


class SyncServer(ThreadingHTTPServer):
    state: SyncState


class SyncHandler(BaseHTTPRequestHandler):
    server: SyncServer

    def log_message(self, _format: str, *_args: object) -> None:
        return None

    def _cors(self) -> None:
        self.send_header("Access-Control-Allow-Origin", "*")
        self.send_header("Access-Control-Allow-Headers", "Content-Type, X-MediaFetch-Nonce")
        self.send_header("Access-Control-Allow-Methods", "POST, OPTIONS")
        self.send_header("Cache-Control", "no-store")

    def do_OPTIONS(self) -> None:  # noqa: N802
        self.send_response(204)
        self._cors()
        self.end_headers()

    def do_POST(self) -> None:  # noqa: N802
        supplied = self.headers.get("X-MediaFetch-Nonce", "")
        expected_path = f"/{self.server.state.nonce}"
        if self.path != expected_path or not hmac.compare_digest(supplied, self.server.state.nonce):
            self.send_error(403)
            return
        try:
            length = int(self.headers.get("Content-Length", "0"))
        except ValueError:
            length = 0
        if length <= 0 or length > MAX_REQUEST_BYTES:
            self.send_error(413)
            return
        try:
            payload = json.loads(self.rfile.read(length))
        except (UnicodeDecodeError, ValueError):
            self.send_error(400)
            return
        self.server.state.synchronize(payload)
        status = 500 if self.server.state.error else 200
        body = json.dumps({"ok": status == 200}).encode()
        self.send_response(status)
        self._cors()
        self.send_header("Content-Type", "application/json")
        self.send_header("Content-Length", str(len(body)))
        self.end_headers()
        self.wfile.write(body)


def _chrome_executable() -> Path:
    candidates = (
        Path(os.environ.get("PROGRAMFILES", "")) / "Google/Chrome/Application/chrome.exe",
        Path(os.environ.get("PROGRAMFILES(X86)", "")) / "Google/Chrome/Application/chrome.exe",
        Path(os.environ.get("LOCALAPPDATA", "")) / "Google/Chrome/Application/chrome.exe",
    )
    for candidate in candidates:
        if candidate.is_file():
            return candidate
    raise RuntimeError("Google Chrome was not found")


def _extension_files(directory: Path, endpoint: str, nonce: str) -> None:
    manifest = {
        "manifest_version": 3,
        "name": "MediaFetch Temporary Cookie Sync",
        "description": "One-time, domain-scoped operator cookie synchronization.",
        "version": "1.0.0",
        "permissions": ["cookies"],
        "host_permissions": [
            "*://*.douyin.com/*",
            "*://*.iesdouyin.com/*",
            "*://*.instagram.com/*",
            "*://*.youtube.com/*",
            "*://*.google.com/*",
            "http://127.0.0.1/*",
        ],
        "background": {"service_worker": "background.js"},
    }
    background = f"""
const endpoint = {json.dumps(endpoint)};
const nonce = {json.dumps(nonce)};
let started = false;
async function synchronize() {{
  if (started) return;
  started = true;
  const roots = {{
    douyin: ["douyin.com", "iesdouyin.com"],
    instagram: ["instagram.com"],
    youtube: ["youtube.com", "google.com"],
  }};
  const payload = {{}};
  for (const [platform, domains] of Object.entries(roots)) {{
    const unique = new Map();
    for (const domain of domains) {{
      const cookies = await chrome.cookies.getAll({{domain}});
      for (const cookie of cookies) {{
        const key = `${{cookie.storeId}}|${{cookie.domain}}|${{cookie.path}}|${{cookie.name}}`;
        unique.set(key, cookie);
      }}
    }}
    payload[platform] = Array.from(unique.values());
  }}
  const response = await fetch(endpoint, {{
    method: "POST",
    headers: {{"Content-Type": "application/json", "X-MediaFetch-Nonce": nonce}},
    body: JSON.stringify(payload),
  }});
  if (response.ok) {{
    await chrome.management.uninstallSelf({{showConfirmDialog: false}});
  }}
}}
synchronize().catch(() => {{ started = false; }});
chrome.runtime.onStartup.addListener(() => synchronize());
chrome.runtime.onInstalled.addListener(() => synchronize());
"""
    (directory / "manifest.json").write_text(json.dumps(manifest, indent=2), encoding="utf-8")
    (directory / "background.js").write_text(background, encoding="utf-8")


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument(
        "--base-url",
        default="https://mnzo.de",
    )
    parser.add_argument("--timeout", type=int, default=120)
    return parser.parse_args()


def main() -> int:
    args = parse_args()
    token = os.environ.get("MEDIAFETCH_ADMIN_TOKEN", "").strip()
    if len(token) < 32:
        print("缺少 MEDIAFETCH_ADMIN_TOKEN", file=sys.stderr)
        return 2
    nonce = secrets.token_urlsafe(32)
    state = SyncState(nonce, args.base_url, token)
    server = SyncServer(("127.0.0.1", 0), SyncHandler)
    server.state = state
    server_thread = threading.Thread(target=server.serve_forever, daemon=True)
    server_thread.start()
    endpoint = f"http://127.0.0.1:{server.server_port}/{nonce}"

    try:
        with tempfile.TemporaryDirectory(prefix="mediafetch-cookie-extension-") as temporary:
            extension = Path(temporary)
            _extension_files(extension, endpoint, nonce)
            print(f"临时扩展目录：{extension}", flush=True)
            subprocess.Popen(
                [
                    str(_chrome_executable()),
                    f"--load-extension={extension}",
                    "--no-first-run",
                    "--no-default-browser-check",
                    "chrome://extensions/",
                ],
                stdout=subprocess.DEVNULL,
                stderr=subprocess.DEVNULL,
            )
            if not state.finished.wait(max(30, args.timeout)):
                print("等待临时扩展响应超时", file=sys.stderr)
                return 3
    finally:
        server.shutdown()
        server.server_close()

    if state.error:
        print(f"同步失败：{state.error}", file=sys.stderr)
        return 4
    for platform in PLATFORM_DOMAINS:
        count, configured = state.result.get(platform, (0, False))
        print(f"{platform}: {count} 个 Cookie，{'同步成功' if configured else '没有可用会话'}")
    return 0 if any(configured for _, configured in state.result.values()) else 5


if __name__ == "__main__":
    raise SystemExit(main())
